version: 1
loggers:
    default:
        handlers: [consoleHandler, fileHandler]
        level: DEBUG
handlers:
    consoleHandler:
        class: logging.StreamHandler
        level: DEBUG
        formatter: brief
    fileHandler:
        class: logging.FileHandler
        formatter: fileformat
        filename: 'log/log.log'
        level: DEBUG
        mode: 'a' #'w'
formatters:
    brief:
        format: '[%(name)-8s|%(levelname)s|%(filename)s:%(lineno)s] %(message)s'
    fileformat:
        format: '[%(name)-8s|%(levelname)s|%(filename)s:%(lineno)s] %(asctime)s > %(message)s'

